services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      # Mount for development hot-reloading (optional)
      # - ./src:/app/src
      # For persisting any app data if needed
      - app-data:/app/data

volumes:
  app-data:
    driver: local
